version: "3"
services:
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    container_name: delivery_frontend
    command: npm start 

  backend:
    build: ./back-end
    working_dir: /app-backend
    container_name: delivery_api
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      API_PORT: 3001
      HOSTNAME: db
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: passmybdindocker
      MYSQL_DB_NAME: delivery-app
    command: npm start    

  db:
    container_name: delivery_db
    image: mysql
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passmybdindocker
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 30s
      retries: 10
